apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          hostNetwork: true
          containers:
            - name: zad2gitops 
              image: ed358/zad2gitops:latest
              command:
                - /bin/sh
                - -c
                - |
                  git clone https://github.com/edlay17/config-kubernetes.git /temp
                  kubectl apply -f /temp/deployment.yaml
                  kubectl apply -f /temp/ingress.yaml  
                  kubectl apply -f /temp/service.yaml