FROM alpine:latest

RUN apk add --no-cache git curl

RUN apk --no-cache add --virtual build-dependencies \
    && curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl \
    && apk del build-dependencies

CMD ["sh"]